import enum
from datetime import datetime, timezone

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app.extensions import db


def utcnow():
    return datetime.now(timezone.utc)


class UserStatus(str, enum.Enum):
    ACTIVE = "active"
    DORMANT = "dormant"      # auto-suspended after too many reports
    BANNED = "banned"        # manually banned by an admin


class ProductStatus(str, enum.Enum):
    ACTIVE = "active"
    SOLD = "sold"
    BLOCKED = "blocked"      # auto-hidden after too many reports, or admin action


class TargetType(str, enum.Enum):
    USER = "user"
    PRODUCT = "product"


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), unique=True, nullable=False, index=True)
    password_hash = db.Column(db.String(255), nullable=False)
    bio = db.Column(db.String(500), default="", nullable=False)
    balance = db.Column(db.Integer, default=0, nullable=False)  # in-platform points, not real money
    is_admin = db.Column(db.Boolean, default=False, nullable=False)
    status = db.Column(db.Enum(UserStatus), default=UserStatus.ACTIVE, nullable=False)
    report_count = db.Column(db.Integer, default=0, nullable=False)
    created_at = db.Column(db.DateTime, default=utcnow, nullable=False)

    products = db.relationship("Product", backref="seller", lazy="dynamic",
                                foreign_keys="Product.seller_id")

    def set_password(self, raw_password: str) -> None:
        # PBKDF2-SHA256 w/ per-password salt, generated by Werkzeug.
        # Never store or log the plaintext password anywhere else.
        self.password_hash = generate_password_hash(raw_password, method="pbkdf2:sha256:600000")

    def check_password(self, raw_password: str) -> bool:
        return check_password_hash(self.password_hash, raw_password)

    @property
    def is_active(self):
        # Overrides UserMixin.is_active: dormant/banned accounts cannot
        # maintain an authenticated session even if the cookie is still valid.
        return self.status == UserStatus.ACTIVE

    def __repr__(self):
        return f"<User {self.username}>"


class Product(db.Model):
    __tablename__ = "products"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(2000), nullable=False, default="")
    price = db.Column(db.Integer, nullable=False)
    image_filename = db.Column(db.String(255), nullable=True)
    seller_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False, index=True)
    status = db.Column(db.Enum(ProductStatus), default=ProductStatus.ACTIVE, nullable=False)
    report_count = db.Column(db.Integer, default=0, nullable=False)
    created_at = db.Column(db.DateTime, default=utcnow, nullable=False)

    def __repr__(self):
        return f"<Product {self.title}>"


class Message(db.Model):
    """Both the global chat and 1:1 DMs are stored here, distinguished by `room`.
    room == 'global'            -> everyone can read/write
    room == 'dm:<min_id>:<max_id>' -> only the two participants may read/write
    """
    __tablename__ = "messages"

    id = db.Column(db.Integer, primary_key=True)
    room = db.Column(db.String(64), nullable=False, index=True)
    sender_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    body = db.Column(db.String(1000), nullable=False)
    created_at = db.Column(db.DateTime, default=utcnow, nullable=False)

    sender = db.relationship("User", foreign_keys=[sender_id])

    @staticmethod
    def dm_room(user_id_a: int, user_id_b: int) -> str:
        lo, hi = sorted([user_id_a, user_id_b])
        return f"dm:{lo}:{hi}"


class Report(db.Model):
    __tablename__ = "reports"

    id = db.Column(db.Integer, primary_key=True)
    reporter_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    target_type = db.Column(db.Enum(TargetType), nullable=False)
    target_id = db.Column(db.Integer, nullable=False)
    reason = db.Column(db.String(500), nullable=False)
    resolved = db.Column(db.Boolean, default=False, nullable=False)
    created_at = db.Column(db.DateTime, default=utcnow, nullable=False)

    reporter = db.relationship("User", foreign_keys=[reporter_id])

    __table_args__ = (
        # A given user can only report the same target once (no spamming reports
        # to force an auto-block of an innocent user/product).
        db.UniqueConstraint("reporter_id", "target_type", "target_id", name="uq_report_once"),
    )


class Transaction(db.Model):
    __tablename__ = "transactions"

    id = db.Column(db.Integer, primary_key=True)
    sender_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    receiver_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    amount = db.Column(db.Integer, nullable=False)
    memo = db.Column(db.String(200), default="", nullable=False)
    created_at = db.Column(db.DateTime, default=utcnow, nullable=False)

    sender = db.relationship("User", foreign_keys=[sender_id])
    receiver = db.relationship("User", foreign_keys=[receiver_id])
